"use client";

import { Gowun_Dodum } from "next/font/google";
import ChatNaviButton from "./ChatNaviButton";
import ChatWindow from "./ChatWindow";
import FriendBar from "./FriendBar";
import FriendNaviButton from "./FriendNaviButton";
import TitleBar from "./TitleBar";
import "./globals.css";
import { RecoilRoot } from "recoil";
import { NextAuthProvider } from "./providers";

const inter = Gowun_Dodum({ subsets: ["latin"], weight: "400" });

// !: 클라이언트 컴포넌트에서 허용되지 않음. 추후 SEO를 위해 서버컴포넌트로 재전환해야함.
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <section id="layout">
            <RecoilRoot>
              <TitleBar />
              <FriendBar />
              <FriendNaviButton />
              <ChatWindow />
              <ChatNaviButton />
            </RecoilRoot>
          </section>
          <section id="body">{props.children}</section>
        </NextAuthProvider>
      </body>
      <style jsx>{`
        #layout {
          display: flex;
          width: 100vw;
          height: 10vh;
        }

        #body {
          display: flex;
          justify-content: center;
        }
      `}</style>
    </html>
  );
}
