"use client";

import { Gowun_Dodum } from "next/font/google";
import ChatNaviButton from "./ChatNaviButton";
import ChatWindow from "./ChatWindow";
import FriendBar from "./FriendBar";
import FriendNaviButton from "./FriendNaviButton";
import TitleBar from "./TitleBar";
import "./globals.css";
import { RecoilRoot } from "recoil";

const inter = Gowun_Dodum({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          <RecoilRoot>
            <TitleBar />
            <FriendBar />
            <FriendNaviButton />
            <ChatWindow />
            <ChatNaviButton />
          </RecoilRoot>
        </section>
        {props.children}
      </body>
      <style jsx>{`
        section {
          display: flex;
          width: 100vw;
          height: 10vh;
        }
      `}</style>
    </html>
  );
}
