// "use client";
// 추후 클라이언트 컴포넌트 집합에 Redux를 사용할때 주석해제
import { Providers } from "@/redux/provider";
import { Gowun_Dodum } from "next/font/google";
import ChatNaviButton from "./ChatNaviButton";
import ChatWindow from "./ChatWindow";
import FriendBar from "./FriendBar";
import TitleBar from "./TitleBar";
import "./globals.css";

const inter = Gowun_Dodum({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TitleBar />
        <section className="flex w-full h-full">
          <FriendBar />
          {props.children}
          <Providers>
            <ChatWindow />
            <ChatNaviButton />
          </Providers>
        </section>
      </body>
    </html>
  );
}
